# common
model_name: autobot
num_modes: 6
hidden_size: 256
num_encoder_layers: 2
num_decoder_layers: 2
tx_hidden_size: 384
tx_num_heads: 16
dropout: 0.2
entropy_weight: 20
kl_weight: 10
use_FDEADE_aux_loss: True

# train
max_epochs: 100 #150 #40
learning_rate: 0.00075 # 0.00075 # 1e-3 for lanegcn
learning_rate_sched: [ 20, 40, 60, 80 ]
optimizer: Adam #According to PyTorch naming
scheduler: multistep # plateau, multistep
ewc_lambda: 2000
train_batch_size: 64 #32 #128
eval_batch_size: 64 #32 #128
grad_clip_norm: 5

# data related
max_num_agents: 15
map_range: 100
max_num_roads: 256
max_points_per_lane: 20 # will be overwritten if manually_split_lane is True
# lane split related params
manually_split_lane: False # if True, lanes will be split with the same number of points and length, else, lanes will be split with the same number of points but varying length
point_sampled_interval: 1 # only used when manually_split_lane is True, the interval of points sampled from the original lane
num_points_each_polyline: 20 # only used when manually_split_lane is True, the number of points in each polyline
vector_break_dist_thresh: 1.0 # only used when manually_split_lane is True, the distance threshold to break the vector to split the lane



